package com.seki.saezurishiki.model.adapter;


public enum ModelActionType {
    LOAD_TWEET,
    LOAD_HOME_LIST,
    LOAD_REPLY_LIST,
    LOAD_TWEET_LIST,
    LOAD_FAVORITE_LIST,

    RECEIVE_TWEET,
    RECEIVE_FAVORITE,
    RECEIVE_UN_FAVORITE,
    RECEIVE_DELETION,

    POST_TWEET,
    UPDATE_TWEET,
    DELETE_TWEET,

    LOAD_FOLLOWS,
    LOAD_FOLLOWERS,

    LOAD_MESSAGES,

    SEND_MESSAGE,

    COMPLETE_FAVORITE,
    COMPLETE_UN_FAVORITE,
    COMPLETE_RETWEET,
    COMPLETE_DELETE_TWEET,

    ERROR,
}
