package com.seki.saezurishiki.model.adapter;

/**
 * Created by seki on 2017/01/22.
 */

public enum ModelActionType {
    LOAD_TWEET,
    LOAD_REPLY,
    LOAD_TWEETS,
    LOAD_FAVORITE,

    REVIEVE_TWEET,
    RECIEVE_FAVOTIE,
    RECIEVE_UN_FAVORITE,
    RECIEVE_DELETION,

    POST_TWEET,
    UPDATE_TWEET,
    DELETE_TWEET,

    LOAD_FOLLOWS,
    LOAD_FOLLOWERS,

    LOAD_MESSAGES,

    SEND_MESSAGE,

    COMPLETE_FAVORITE,
    COMPLETE_UN_FAVORITE,
    COMPLETE_RETWEET,
    COMPLETE_DELETE_TWEET,

    ERROR,
}
